# Generated by Django 3.1.3 on 2022-09-28 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0005_answer_voter_question_voter_alter_answer_author_and_more'),
        ('pybo', '0006_comment'),
    ]

    operations = [
    ]
