# Generated by Django 3.1.3 on 2022-09-28 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_merge_20220928_1330'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
